version: '2'

services:
  db:
    image: mysql:5
    environment:
      - MYSQL_ROOT_PASSWORD=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=app
      - MYSQL_DATABASE=app
  magento-neo4j:
    image: asarturas/magento-nginx
    links:
      - app
    ports:
      - "80:80"
    volumes_from:
      - data
    working_dir: /var/www/app
  app:
    image: asarturas/magento-php-fpm
    links:
      - db
    volumes_from:
      - data
    environment:
      - APP_HOSTNAME=magento-neo4j
  data:
    image: debian
    volumes:
      - ".:/var/www/app"
  neo4j:
    image: neo4j
    ports:
      - "7474:7474"
  selenium:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
    entrypoint: "/opt/bin/entry_point.sh"
