version: '2'

services:
  data:
    image: debian
    volumes:
      - ".:/var/www/app"
  db:
    image: mysql:5
    environment:
      - MYSQL_ROOT_PASSWORD=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=app
      - MYSQL_DATABASE=app
    volumes:
      - "./docker/mysql-data:/shared-mysql-data"
  app:
    image: php:5.5-fpm
    ports:
      - "9000:9000"
    volumes:
      - "./docker/php-config:/shared-php-config"
#      - "./docker/php-config/php-fpm.conf:/etc/php5/fpm/php-fpm.conf"
#      - "./docker/php-config/www.conf:/etc/php5/fpm/pool.d/www.conf"
    volumes_from:
      - data
    working_dir: /var/www/app
    entrypoint: ./docker/start-app.sh
  server:
    image: nginx
    links:
      - app
    ports:
      - "80:80"
    volumes:
      - "./docker/nginx-config/default.conf:/etc/nginx/conf.d/default.conf"
      - "./docker/nginx-config/nginx.conf:/etc/nginx/nginx.conf"
    volumes_from:
      - data
    working_dir: /var/www/app
  neo4j:
    image: neo4j
  selenium:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
    volumes:
      - "./docker/selenium/setup-host.sh:/setup-host.sh"
    entrypoint: "/setup-host.sh"
