data:
  image: debian
  volumes:
    - ".:/var/www/app"
server:
  image: nginx
  links:
    - app
  ports:
    - "80:80"
  volumes:
    - "./docker/nginx-config/default.conf:/etc/nginx/conf.d/default.conf"
    - "./docker/nginx-config/nginx.conf:/etc/nginx/nginx.conf"
  volumes_from:
    - data
  working_dir: /var/www/app
app:
  image: php:5.5-fpm
  links:
    - db
    - neo4j
    - selenium
  ports:
    - "9000:9000"
  volumes:
    - "./docker/php-config/php-fpm.conf:/etc/php5/fpm/php-fpm.conf"
    - "./docker/php-config/www.conf:/etc/php5/fpm/pool.d/www.conf"
  volumes_from:
    - data
  working_dir: /var/www/app
  entrypoint: ./start-app.sh
db:
  image: mysql:5
  environment:
    - MYSQL_ROOT_PASSWORD=app
    - MYSQL_USER=app
    - MYSQL_PASSWORD=app
    - MYSQL_DATABASE=app
  volumes:
    - "./docker/mysql-data:/shared-mysql-data"
neo4j:
  image: neo4j
selenium:
  image: selenium/standalone-chrome
  ports:
    - "4444:4444"
